### ISSUE TITLE
Epic Games Feed Using Wrong URL

### ISSUE THREAD

**Issue by Menteroth** [eikowagenknecht/lootscraper#448]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

https://www.epicgames.com/site/en-US/p/thems-fightin-herds/home
![Image](https://github.com/user-attachments/assets/23dc140a-1f9f-428c-a84c-ecb6bbcb9a6a)

Instead of https://store.epicgames.com/en-US/p/thems-fightin-herds

**Comment by eikowagenknecht** [comment]
Thanks! Seems to be another case of "The Epic API is weird". For some games, the "productSlug" is the correct URL and the "urlSlug" is wrong, for others it's exactly the other way around...

This weeks game:
![Image](https://github.com/user-attachments/assets/f765ac26-1efb-4cd9-b765-1174b8b972ce)

Next weeks game:

![Image](https://github.com/user-attachments/assets/317784a5-6ff4-4c42-b83c-13b0fd9b7921)

**Comment by eikowagenknecht** [comment]
Maybe fixed with 906642f4e721fff106362f75ef21a10f0995c05b, now I'm looking at opperMappings > 0 > pageSlug first if it exists and only fall back to the main pageSlug otherwise. For those two games it will work, but I can't guarantee for all that are to come. Please ping me if it happens again.

**Comment by PhilC813** [comment]
The URL is still incorrect for the referenced game. Not sure if that's normal.

**Comment by eikowagenknecht** [comment]
Hey @PhilC813, yes that was to be expected as existing offers are not reevaluated. But I've fixed it manually in the db now, it should update soon :-)
